name: Set environment variables

on: [push]

jobs:
  setter:
    runs-on: ubuntu-latest
    env:
      AES_PHONE_SECRET_KEY: ${{ secrets.AES_PHONE_SECRET_KEY }}
      AES_ADDRESS_SECRET_KEY: ${{ secrets.AES_ADDRESS_SECRET_KEY }}

    steps:
      - name: secret keys go brrr
        run: echo "keys are set"
